version: '3.7'
services:
  compiler:
    build:
      context: ./docker/compiler
    volumes:
      - ./src:/src
    # environment:
    #   - http_proxy=http://host.docker.internal:7890
    #   - https_proxy=http://host.docker.internal:7890
    entrypoint: 
      - /bin/sh
      - -c 
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && tail -f /dev/null
