#!/bin/sh
uci del dhcp.lan.dhcpv6
uci set network.lan.ipaddr='192.168.8.1'
uci del network.lan.ifname

uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-iface[0].disabled=0
uci set wireless.@wifi-iface[0].ssid='ot1m_br'
uci set wireless.@wifi-iface[0].key='12345678'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.sta.disabled=1
uci commit

# uci set firewall.cfg03dc81.network='wan wan6 WWAN'
# uci set network.WWAN=interface
# uci set network.WWAN.proto='qmi'
# uci set network.WWAN.device='/dev/cdc-wdm0'
# uci set network.WWAN.delegate='0'
# uci set network.WWAN.pdptype='ipv4'
# uci set network.WWAN.auth='none'
# uci commit

uci set network.wan=interface
uci set network.wan.ifname='eth0'
uci set network.wan.proto='static'
uci set network.wan.ipaddr='172.16.1.218'
uci set network.wan.gateway='172.16.0.1'
uci set network.wan.delegate='0'
uci add_list network.wan.dns='119.29.29.29'
uci set network.wan.netmask='255.255.254.0'
uci commit
